(define (problem SPANNER-10)
 (:domain SPANNER)
 (:objects 
     bob - man
     spanner1 spanner2 spanner3 spanner4 spanner5 spanner6 spanner7 spanner8 spanner9 spanner10 spanner11 spanner12 spanner13 spanner14 spanner15 spanner16 spanner17 spanner18 spanner19 spanner20 - spanner
     nut1 nut2 nut3 nut4 nut5 nut6 nut7 nut8 nut9 nut10 nut11 nut12 nut13 nut14 nut15 nut16 nut17 nut18 nut19 nut20 - nut
     location1 location2 location3 location4 location5 location6 location7 location8 location9 location10 - location
)
 (:init 
    (atm bob location1)
    (ats spanner1 location5)
    (useable spanner1)
    (ats spanner2 location10)
    (useable spanner2)
    (ats spanner3 location4)
    (useable spanner3)
    (ats spanner4 location1)
    (useable spanner4)
    (ats spanner5 location9)
    (useable spanner5)
    (ats spanner6 location8)
    (useable spanner6)
    (ats spanner7 location5)
    (useable spanner7)
    (ats spanner8 location8)
    (useable spanner8)
    (ats spanner9 location5)
    (useable spanner9)
    (ats spanner10 location6)
    (useable spanner10)
    (ats spanner11 location9)
    (useable spanner11)
    (ats spanner12 location8)
    (useable spanner12)
    (ats spanner13 location3)
    (useable spanner13)
    (ats spanner14 location3)
    (useable spanner14)
    (ats spanner15 location5)
    (useable spanner15)
    (ats spanner16 location1)
    (useable spanner16)
    (ats spanner17 location4)
    (useable spanner17)
    (ats spanner18 location5)
    (useable spanner18)
    (ats spanner19 location2)
    (useable spanner19)
    (ats spanner20 location8)
    (useable spanner20)
    (loose nut1)
    (atn nut1 location10)
    (loose nut2)
    (atn nut2 location10)
    (loose nut3)
    (atn nut3 location10)
    (loose nut4)
    (atn nut4 location10)
    (loose nut5)
    (atn nut5 location10)
    (loose nut6)
    (atn nut6 location10)
    (loose nut7)
    (atn nut7 location10)
    (loose nut8)
    (atn nut8 location10)
    (loose nut9)
    (atn nut9 location10)
    (loose nut10)
    (atn nut10 location10)
    (loose nut11)
    (atn nut11 location10)
    (loose nut12)
    (atn nut12 location10)
    (loose nut13)
    (atn nut13 location10)
    (loose nut14)
    (atn nut14 location10)
    (loose nut15)
    (atn nut15 location10)
    (loose nut16)
    (atn nut16 location10)
    (loose nut17)
    (atn nut17 location10)
    (loose nut18)
    (atn nut18 location10)
    (loose nut19)
    (atn nut19 location10)
    (loose nut20)
    (atn nut20 location10)
    (link location1 location2)
    (link location2 location3)
    (link location3 location4)
    (link location4 location5)
    (link location5 location6)
    (link location6 location7)
    (link location7 location8)
    (link location8 location9)
    (link location9 location10)
)
 (:goal
  (and
   (tightened nut1)
   (tightened nut2)
   (tightened nut3)
   (tightened nut4)
   (tightened nut5)
   (tightened nut6)
   (tightened nut7)
   (tightened nut8)
   (tightened nut9)
   (tightened nut10)
   (tightened nut11)
   (tightened nut12)
   (tightened nut13)
   (tightened nut14)
   (tightened nut15)
   (tightened nut16)
   (tightened nut17)
   (tightened nut18)
   (tightened nut19)
   (tightened nut20)
)))
