(define (problem BLOCKS-2)
 (:domain BLOCKS)
 (:objects  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - object)
 (:init 
    (handempty)
    (clear b4)
    (on b4 b11)
    (on b11 b9)
    (on b9 b5)
    (on b5 b10)
    (ontable b10)
    (clear b1)
    (ontable b1)
    (clear b3)
    (on b3 b2)
    (ontable b2)
    (clear b8)
    (on b8 b6)
    (on b6 b7)
    (ontable b7)
)
 (:goal
  (and
   (ontable b1)
   (ontable b2)
   (ontable b3)
   (ontable b4)
   (ontable b5)
   (ontable b6)
   (ontable b7)
   (ontable b8)
   (ontable b9)
   (ontable b10)
   (ontable b11)
)))
