(define (problem BLOCKS-5)
 (:domain BLOCKS)
 (:objects  b1 b2 b3 b4 b5 b6 b7 - object)
 (:init 
    (handempty)
    (clear b2)
    (on b2 b4)
    (on b4 b7)
    (ontable b7)
    (clear b5)
    (on b5 b3)
    (ontable b3)
    (clear b1)
    (ontable b1)
    (clear b6)
    (ontable b6)
)
 (:goal
  (and
   (ontable b1)
   (ontable b2)
   (ontable b3)
   (ontable b4)
   (ontable b5)
   (ontable b6)
   (ontable b7)
)))
