;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain ARC)
    (:requirements :equality :typing)
    (:types
        output_pixels - object
        color - object
        object
    )

    (:constants
        
    )

    (:predicates
        (painted_output ?x1 - output_pixels ?x2 - color)
        (color_usable ?x1 - color)
    )

    (:functions
        
    )

    

    
    (:action paint
     :parameters (?c - color ?c2 - color ?y - output_pixels)
     :precondition (and (color_usable ?c2) (painted_output ?y ?c))
     :effect (and
        (not (painted_output ?y ?c))
        (painted_output ?y ?c2))
    )

)