(define (problem BLOCKS-4)
 (:domain BLOCKS)
 (:objects  b1 b2 b3 b4 b5 b6 - object)
 (:init 
    (handempty)
    (clear b2)
    (ontable b2)
    (clear b4)
    (ontable b4)
    (clear b3)
    (ontable b3)
    (clear b5)
    (ontable b5)
    (clear b1)
    (on b1 b6)
    (ontable b6)
)
 (:goal
  (and
   (ontable b1)
   (ontable b2)
   (ontable b3)
   (ontable b4)
   (ontable b5)
   (ontable b6)
)))
