(define (problem SPANNER-4)
 (:domain SPANNER)
 (:objects 
     bob - man
     spanner1 spanner2 spanner3 spanner4 spanner5 spanner6 spanner7 spanner8 - spanner
     nut1 nut2 nut3 nut4 nut5 nut6 nut7 nut8 - nut
     location1 location2 location3 location4 - location
)
 (:init 
    (atm bob location1)
    (ats spanner1 location3)
    (useable spanner1)
    (ats spanner2 location1)
    (useable spanner2)
    (ats spanner3 location1)
    (useable spanner3)
    (ats spanner4 location4)
    (useable spanner4)
    (ats spanner5 location2)
    (useable spanner5)
    (ats spanner6 location2)
    (useable spanner6)
    (ats spanner7 location1)
    (useable spanner7)
    (ats spanner8 location1)
    (useable spanner8)
    (loose nut1)
    (atn nut1 location4)
    (loose nut2)
    (atn nut2 location4)
    (loose nut3)
    (atn nut3 location4)
    (loose nut4)
    (atn nut4 location4)
    (loose nut5)
    (atn nut5 location4)
    (loose nut6)
    (atn nut6 location4)
    (loose nut7)
    (atn nut7 location4)
    (loose nut8)
    (atn nut8 location4)
    (link location1 location2)
    (link location2 location3)
    (link location3 location4)
)
 (:goal
  (and
   (tightened nut1)
   (tightened nut2)
   (tightened nut3)
   (tightened nut4)
   (tightened nut5)
   (tightened nut6)
   (tightened nut7)
   (tightened nut8)
)))
